#!/usr/bin/env python3
"""Build the v15 fingertip asset: PLA spine + TPU 95A blade, the tip the robot now runs.

WHY THIS EXISTS. The rig's fingers are the ORIGINAL one-piece Pika sense arm + pad, dark
grey, rigid, and collided as a SINGLE CONVEX HULL. The robot no longer has that part: the
tip was redesigned as a rigid PLA spine carrying a compliant TPU 95A nose, printed in
#F3E600 yellow, and `data_v2` -- the dataset the served checkpoints are trained on -- was
collected with it. So the old tip is not a conservative default any more; it is a mismatch
against both the hardware and the training distribution, in the ONE part of the scene the
wrist camera never stops seeing and the only part that ever touches a bolt.

This script is stage 1 of the operator's two-stage plan: GEOMETRY AND APPEARANCE ONLY, the
blade still a rigid body. Stage 2 relaxes the contact parameters to stand in for 95A
compliance. Splitting them is deliberate -- shape and softness move grasping in the same
direction, and merged they cannot be told apart.

SOURCE: robotics_lab, NOT the CAD
=================================
The meshes come from
    robotics_lab/rb_servo_server/descriptions/meshes/robots/rb5_850e/visual/tool/
        pika_finger_{left,right}_{pla,tpu}.STL
already in the URDF tool frame, generated by that repo's own
`rb_servo_server/tools/make_pika_tool_meshes.py` (which has a --check mode that byte-
compares the committed meshes against a rebuild). The rb5 directory is not a mistake: the
Pika tool is the same part on both arms, and these meshes are in the attachment_site frame
the rb3 asset also uses -- the seat plane and the TCP land on the rb3 finger's own values.

This rig CONSUMES that placement instead of deriving its own, and the first attempt at
this port is why. Working from the v15 CAD alone it recovered the tip frame correctly (the
same -58.990/-19.055/-44.190 offset, confirmed against the Z = -34.39 seat plane) and then
anchored tip X = 0 to the FACTORY finger's contact plane. Wrong, by ~2 mm per side, and
the tell was visible and dismissed: the spine appeared to sit 1.99 mm proud of the old
envelope at the BACK of the jaw. The part does not overhang at the back -- it seats
somewhere else entirely, because the printed spine's foot was derived from the pika SENSE
arm rather than from the Gripper finger it replaces.

THE JAW IS A MEASUREMENT NOW, NOT A CAD POSE
============================================
robotics_lab first placed the tip from the carriage datums in pika_gripper_base.STL (four
M2 tapped holes plus the rail screw), three of which agreed within 0.046 mm on a 1.991 mm
inboard shift -> a 90.35 mm full-open gap. Hardware then said otherwise:

    2026-09-04, vernier across the two TPU faces: FULL-OPEN GAP ~98 mm, jaws close to
    contact. Not 90.35 (with the shift), not 94.33 (without), not 94.04 (factory).

The premise none of the three shared: THE VENDOR CAD DOES NOT DRAW THE FINGERS AT THE OPEN
STOP -- it draws them ~3.8 mm/side inboard of it. And the old finger travel of 0.047 m was
never measured either; it was picked so that the same undrawn-at-the-stop CAD pose would
close to a zero gap. Two unmeasured numbers had been agreeing with each other.

So the placement is anchored on the measurement, and the carriage stroke FOLLOWS from it:
gap 0 at the closed stop => stroke = gap / 2 = 49.0 mm per side, not 47.0. This build does
not hardcode either number -- it reads the contact face off the mesh and derives the rest,
so whatever robotics_lab lands on arrives here by re-running the script.

    *** CONSEQUENCE FOR THIS RIG: FINGER_TRAVEL_M goes 0.047 -> 0.049. ***

That constant is the jaw model in eval_closed_loop.py (grip proprio, set_arm, and
achieved_gap_mm) and in make_articulated_urdf.py. At 0.047 the sim's jaw would stop 2 mm
per side short of closing, which on an 18.4 mm bolt head is the difference between a grasp
and a miss. The URDF prismatic limit is +-0.05 m, so 0.049 still fits without moving it.

One thing a single gap measurement CANNOT do (robotics_lab's own note, repeated here so it
is not re-litigated): seating shift s and extra opening e appear only as (e - s) = 1.83 mm,
so s = 1.991 / e = 3.83 and s = 0 / e = 1.83 both reproduce 98.0 exactly. Nothing computed
here depends on the split. Do not spend hardware time separating them.

NO MESH SURGERY -- the spine STL is used verbatim
=================================================
`PLA_spine_v15.STL` is not a clean solid. It is an externally revised export carrying
boolean residue: 5 connected components and 10 non-manifold (valence-4) edges in the foot
boss, comprising a duplicated planar slab pair whose volumes nearly cancel and one inverted
shell that is an interior void wall.

An earlier version of this script removed them. It no longer does, on the operator's
instruction and for a good reason: THIS FILE IS WHAT WAS PRINTED. The slicer consumed these
exact triangles, so the physical part on the robot is whatever this mesh means, residue
included. A tidier mesh here would be a different part from the one being modelled.

Checked before accepting it, because "use it as-is" still has to be safe:
    convex hull   91684.911 mm3 both ways -- BIT-IDENTICAL, so the collider is unaffected
    volume        35909.5 raw vs 35862.7 cleaned = 0.13%, i.e. nothing for mass
    the strays    all interior: the slab pair sits ON an internal wall (signed distance
                  0.00 mm) and the inverted shell 1.75-2.86 mm inside the body
So the residue cannot reach the collider, cannot reach the outer silhouette, and cannot
move the mass. The build still PRINTS the component inventory every time, so the file's
condition stays on the record rather than becoming folklore.

COLLISION. The old collider was `physics:approximation = "convexHull"` over the whole
finger: 119262 mm3 against a true 31039, i.e. 3.8x, with the contact face flattened into
one plane. That erases exactly what the redesign is FOR -- the 2.0 mm retention arch.
Measured here by ray-casting the contact profile at Y = 0:
    true arch amplitude over Z_tip >= 50   2.062 mm
    single convex hull                     0.139 mm   (what the rig had: 7% left)
So the blade gets an SDF collider, which keeps the authored surface to within a voxel.
The convex decomposition tried first is kept only as an A/B partner (TIP_COLLISION=decomp)
and is NOT the default: coacd returned 24/25/27/29 parts across runs from one mesh and one
seed, and put a part 0.44 mm proud of the true surface. A collider that moves when you
rebuild it has no place in a rig whose whole value is that two runs are comparable.

The spine keeps a convex hull: its own front face sits ~7.9 mm behind the blade's contact
face, so hulling it cannot add material anywhere an object can reach.

MASS. The finger links carry PhysicsRigidBodyAPI with NO explicit mass, so PhysX derived
it from the collider -- from that 3.8x-inflated hull, giving 119.3 g. Leaving it derived
would silently move the mass again whenever the collider changes, so it is now explicit.

The infill of the printed parts is not known, so the density used is SOLID material and
the resulting 55.7 g/finger is an UPPER BOUND -- the real part is lighter by whatever the
sparse infill saves. That is still far closer than what the rig had (119.3 g was over
double a solid part). TIP_DENSITY_PLA / TIP_DENSITY_TPU are the knobs. The number that
would settle it is a measurement, not a guess: robotics_lab owes a hardware `ft identify`
re-run for tool_mass_kg after this swap, and that reading can be divided down to here.

Run:  .venv-isaac/bin/python scripts/build_tip_v15.py
"""
from __future__ import annotations

import argparse
import hashlib
import os
import pathlib

import numpy as np
import trimesh

ROOT = pathlib.Path(__file__).resolve().parent.parent
TOOL = (pathlib.Path.home() / "workspace/robotics_lab/rb_servo_server/descriptions/meshes"
        / "robots/rb5_850e/visual/tool")

OUT_MESH = ROOT / "assets/meshes/tip_v15"
# ARM is a knob since the 2026-09-05 RB3 -> RB5 port: the tip is the SAME PART on both arms
# (robotics_lab keeps one copy, under the rb5 tool directory, and both arm URDFs point at
# it), so only the asset this tip is grafted onto changes.
ARM = os.environ.get("SIM_ARM", "rb5_850e").lower()
SRC_ASSET = ROOT / f"assets/{ARM}_pika_articulated_sim"
OUT_ASSET = ROOT / f"assets/{ARM}_pika_tip_v15"

# What robotics_lab's generator puts in the tool frame, in mm. Gate targets, not inputs --
# if a rebuild there moves them, this build says so instead of quietly following.
SEAT_Z = 135.524          # carriage seat plane
TIP_Z = 247.578           # blade tip; the URDF TCP is 247.642, i.e. 0.064 behind it
TCP_Z = 247.642
WIDTH_Y = 38.118
# The blade contact face |X| is NOT hardcoded. It is where robotics_lab's placement puts
# it, and that placement is now anchored on a HARDWARE MEASUREMENT (2026-09-04, vernier
# across the two TPU faces: full-open gap ~98 mm, jaws closing to contact) rather than on
# the vendor CAD pose -- the CAD turned out not to draw the fingers at the open stop, and
# the old 0.047 travel had been picked to make that unmeasured pose close to zero.
# So: gap = 2 x |X|, and the carriage stroke FOLLOWS from it (gap 0 at the closed stop =>
# stroke = gap / 2). Reading it off the mesh is what keeps this rig from re-deriving a
# number the robot measures. Sanity band only.
CONTACT_X_RANGE = (40.0, 55.0)

# BLADE COLLISION. `sdf` (default) keeps the authored surface and is reproducible; `decomp`
# is the coacd convex decomposition, kept only as the A/B partner -- see COLLISION above.
TIP_COLLISION = os.environ.get("TIP_COLLISION", "sdf").lower()
TIP_SDF_RES = int(os.environ.get("TIP_SDF_RES", "256"))
COACD_THRESHOLD = float(os.environ.get("TIP_COACD_THRESHOLD", "0.05"))
DENSITY_PLA = float(os.environ.get("TIP_DENSITY_PLA", "1240.0"))   # kg/m^3, solid PLA
DENSITY_TPU = float(os.environ.get("TIP_DENSITY_TPU", "1200.0"))   # kg/m^3, solid TPU 95A

# #F3E600, the filament the blade is printed in. The asset's own materials are in LINEAR
# space (gray_80 stores 0.6038 for sRGB 0.8), so convert rather than pasting 0.95.
TPU_SRGB = (0xF3 / 255.0, 0xE6 / 255.0, 0x00 / 255.0)
# The spine keeps the colour the original finger had (materials.usda `gray_30`), which is
# also what robotics_lab's display URDF calls the PLA. One line to change if it is not black.
PLA_LINEAR = (0.07323897, 0.07323897, 0.07323897)


def srgb_to_linear(c: float) -> float:
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def describe(m: trimesh.Trimesh, label: str) -> trimesh.Trimesh:
    """Report the mesh's condition. Does NOT modify it -- see NO MESH SURGERY."""
    m = m.copy()
    m.merge_vertices()
    comps = sorted(m.split(only_watertight=False), key=lambda c: -abs(c.volume))
    if len(comps) > 1:
        print(f"  [{label}] {len(comps)} components, watertight={m.is_watertight} "
              f"(kept verbatim):")
        body = comps[0]
        for c in comps[1:]:
            d = trimesh.proximity.ProximityQuery(body).signed_distance(c.vertices)
            print(f"        vol {c.volume:+9.1f} mm3  {len(c.faces):4d} tris  "
                  f"{float(np.percentile(d, 50)):+.2f} mm inside the body surface")
    return m


def contact_profile(meshes, zs, y=0.0):
    """The X a LEFT-finger contact face presents at (y, z): shoot from the centreline
    outward and keep the first surface. Ray-cast, because the contact faces are flat and
    carry vertices only at their edges -- a vertex-band probe reads nothing there and
    returned all-NaN on the first attempt."""
    org = np.column_stack([np.full(len(zs), 50.0), np.full(len(zs), y), zs])
    dirs = np.tile([-1.0, 0.0, 0.0], (len(zs), 1))
    best = np.full(len(zs), np.nan)
    for m in meshes:
        loc, idx, _ = m.ray.intersects_location(org, dirs, multiple_hits=False)
        for L, i in zip(loc, idx):
            if np.isnan(best[i]) or L[0] > best[i]:
                best[i] = L[0]
    return best


def decompose(mesh: trimesh.Trimesh, threshold: float):
    import coacd
    coacd.set_log_level("error")
    parts = coacd.run_coacd(coacd.Mesh(mesh.vertices, mesh.faces),
                            threshold=threshold, seed=0, merge=True)
    return [trimesh.Trimesh(np.asarray(v), np.asarray(f)) for v, f in parts]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--meshes-only", action="store_true",
                    help="write the STLs and the gate report, skip the USD asset")
    args = ap.parse_args()

    print("== source: robotics_lab tool meshes (generated by make_pika_tool_meshes.py)")
    parts, prov = {}, {}
    for side in ("left", "right"):
        parts[side] = {}
        for kind in ("pla", "tpu"):
            p = TOOL / f"pika_finger_{side}_{kind}.STL"
            if not p.exists():
                print(f"FAIL: missing {p}\n      run robotics_lab's "
                      f"rb_servo_server/tools/make_pika_tool_meshes.py first")
                return 1
            prov[p.name] = hashlib.md5(p.read_bytes()).hexdigest()
            parts[side][kind] = describe(trimesh.load(p, force="mesh"), f"{side[0]}/{kind}")
    for k, v in sorted(prov.items()):
        print(f"  {k:28s} md5 {v}")

    L = parts["left"]
    print(f"  pla {L['pla'].volume:8.1f} mm3  tpu {L['tpu'].volume:8.1f} mm3  "
          f"(blade watertight {L['tpu'].is_watertight})")

    # ---- gates ------------------------------------------------------------------------
    asm = trimesh.util.concatenate([L["pla"], L["tpu"]])
    al, ah = asm.bounds
    print("\n== placement gates (left finger, tool frame, mm)")
    checks = [
        ("seat plane   Zmin", al[2], SEAT_Z, 0.01),
        ("tip plane    Zmax", ah[2], TIP_Z, 0.01),
        ("width            ", ah[1] - al[1], WIDTH_Y, 0.01),
    ]
    ok = True
    for name, got, want, tol in checks:
        good = abs(got - want) <= tol
        ok &= good
        print(f"  {name:18s} {got:9.3f}  vs {want:9.3f}  ({got - want:+6.3f}, tol {tol})"
              f"  {'PASS' if good else 'FAIL'}")
    if not ok:
        print("FAIL: the Z chain moved. seat/tip/width are the CAD-chain invariants this "
              "port rests on -- re-read robotics_lab's make_pika_tool_meshes.py before "
              "touching the constants here.")
        return 1
    contact_x = abs(ah[0])
    if not CONTACT_X_RANGE[0] <= contact_x <= CONTACT_X_RANGE[1]:
        print(f"FAIL: blade contact face |X| = {contact_x:.3f} is outside the sanity band "
              f"{CONTACT_X_RANGE} -- that is not a jaw.")
        return 1
    print(f"  TCP clearance      {TCP_Z - ah[2]:9.3f}  the blade ends behind the URDF TCP; "
          f"tcp_joint is deliberately unchanged (0.064 mm in a 247.642 chain)")

    # left/right are generated with separate transforms (-47.0162 / +47.0138), so they are
    # near-mirrors, not exact ones. Check the asymmetry is at CAD-fit level, not a sign slip.
    for kind in ("pla", "tpu"):
        lb, rb = parts["left"][kind].bounds, parts["right"][kind].bounds
        skew = max(abs(abs(lb[0][0]) - rb[1][0]), abs(abs(lb[1][0]) - rb[0][0]))
        print(f"  left/right {kind} X asymmetry {skew:.4f} mm  "
              f"{'PASS' if skew < 0.05 else 'FAIL'}")
        if skew >= 0.05:
            return 1

    gap_open = 2.0 * contact_x
    travel_mm = gap_open / 2.0
    print("\n== jaw")
    print(f"  full-open gap        {gap_open:7.3f} mm   (factory finger: 94.04)")
    print(f"  carriage stroke      {travel_mm:7.3f} mm/side, DERIVED from it (gap 0 at the "
          f"closed stop)")
    print(f"  the rig hardcodes FINGER_TRAVEL_M = 0.047 in eval_closed_loop.py and "
          f"make_articulated_urdf.py.")
    print(f"  -> both must read {travel_mm / 1000.0:.3f}. 0.047 was never measured; it was "
          f"chosen so the vendor CAD pose would close to zero, and the CAD does not draw "
          f"the fingers at the open stop.")
    print(f"  URDF prismatic limit is +-0.05 m, so {travel_mm / 1000.0:.3f} still fits "
          f"({'PASS' if travel_mm <= 50.0 else 'FAIL -- the joint limit must move too'})")

    # ---- collision --------------------------------------------------------------------
    print(f"\n== collision (blade: {TIP_COLLISION})")
    pla_hull = {s: parts[s]["pla"].convex_hull for s in parts}
    zs = np.arange(30.0, 68.1, 2.0) + (TIP_Z - 67.86)   # tip-frame Z -> tool frame
    truth = contact_profile([L["tpu"]], zs)
    hull = contact_profile([L["tpu"].convex_hull], zs)
    seg = zs >= 50.0 + (TIP_Z - 67.86)
    amp = lambda p: float(np.nanmax(p[seg]) - np.nanmin(p[seg]))
    tpu_parts = {s: [] for s in parts}
    print("  retention-arch amplitude over Z_tip>=50 (the feature the redesign is FOR):")
    print(f"     true mesh          {amp(truth):.3f} mm")
    print(f"     single convex hull {amp(hull):.3f} mm   (what the rig had -- arch gone)")
    if TIP_COLLISION == "decomp":
        tpu_parts = {s: decompose(parts[s]["tpu"], COACD_THRESHOLD) for s in parts}
        got = contact_profile(tpu_parts["left"], zs)
        print(f"     decomposition      {amp(got):.3f} mm   "
              f"({100 * amp(got) / amp(truth):.0f}% preserved, {len(tpu_parts['left'])} parts, "
              f"max {float(np.nanmax(got - truth)):.2f} mm proud)")
        print("  WARNING: coacd is NOT reproducible -- one mesh and one seed gave 24/25/27/29 "
              "parts across runs. Frozen on disk here, but a rebuild moves the jaw.")
        if amp(got) < 0.6 * amp(truth):
            print("FAIL: the decomposition flattened the arch; lower TIP_COACD_THRESHOLD")
            return 1
    else:
        ext = float(np.max(L["tpu"].extents))
        print(f"     sdf res {TIP_SDF_RES}      exact to ~{ext / TIP_SDF_RES:.3f} mm "
              f"(one voxel across the blade's {ext:.1f} mm long axis)")
    print(f"  pla hull front |X| {abs(pla_hull['left'].bounds[1][0]):.2f} vs blade contact "
          f"{contact_x:.2f} -- hull stays "
          f"{abs(pla_hull['left'].bounds[1][0]) - contact_x:.2f} mm behind it")

    # ---- mass -------------------------------------------------------------------------
    m_pla = L["pla"].volume * 1e-9 * DENSITY_PLA
    m_tpu = L["tpu"].volume * 1e-9 * DENSITY_TPU
    mass = m_pla + m_tpu
    old = trimesh.load(TOOL / "pika_finger_left_hull.STL", force="mesh")
    print("\n== mass per finger")
    print(f"  pla {L['pla'].volume:8.1f} mm3 x {DENSITY_PLA:.0f} = {m_pla * 1e3:6.2f} g")
    print(f"  tpu {L['tpu'].volume:8.1f} mm3 x {DENSITY_TPU:.0f} = {m_tpu * 1e3:6.2f} g")
    print(f"  total {mass * 1e3:.2f} g, set EXPLICITLY (the rig's old finger was "
          f"{119.3:.1f} g, derived by PhysX from a hull 3.8x the true volume)")
    print("  UPPER BOUND: solid-material densities, infill unknown. The real parts are "
          "lighter by whatever\n  the sparse infill saves -- still far closer than the "
          "119.3 g the rig was using. A hardware\n  `ft identify` (robotics_lab owes one "
          "after this swap) settles it; TIP_DENSITY_* are the knobs.")

    # ---- write ------------------------------------------------------------------------
    OUT_MESH.mkdir(parents=True, exist_ok=True)
    for stale in OUT_MESH.glob("tip_v15_*"):
        stale.unlink()
    written = 0
    for side in ("left", "right"):
        for kind in ("pla", "tpu"):
            parts[side][kind].export(OUT_MESH / f"tip_v15_{side}_{kind}.stl")
            written += 1
        pla_hull[side].export(OUT_MESH / f"tip_v15_{side}_pla_col.stl")
        written += 1
        for i, p in enumerate(tpu_parts[side]):
            p.export(OUT_MESH / f"tip_v15_{side}_tpu_col_{i:03d}.stl")
            written += 1
    (OUT_MESH / "PROVENANCE.json").write_text(__import__("json").dumps(
        {"source": str(TOOL), "md5": prov, "collision": TIP_COLLISION,
         "sdf_resolution": TIP_SDF_RES, "mass_kg_per_finger": mass,
         "density_pla": DENSITY_PLA, "density_tpu": DENSITY_TPU,
         "contact_face_mm": contact_x, "full_open_gap_mm": gap_open,
         "finger_travel_m": travel_mm / 1000.0}, indent=1))
    print(f"\n== meshes -> {OUT_MESH.relative_to(ROOT)}: {written} stl + PROVENANCE.json")

    if args.meshes_only:
        return 0
    from build_tip_v15_asset import build_asset
    build_asset(parts, pla_hull, tpu_parts, mass, SRC_ASSET, OUT_ASSET,
                tuple(srgb_to_linear(c) for c in TPU_SRGB), PLA_LINEAR,
                mode=TIP_COLLISION, sdf_res=TIP_SDF_RES)
    return 0


if __name__ == "__main__":
    import sys
    sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
    raise SystemExit(main())
